### ISSUE TITLE
Old Ruby required

### ISSUE THREAD

**Issue by Inversion-des** [vikdotdev/viberroo#14]
This line
`s.required_ruby_version = '~> 2.3'`
causes `gem install` to install some old version when I'm on Ruby 3.
Is there any reason for that? Works fine for me on the latest Ruby (cloned the repo to use it).

Thank you for the gem!

**Comment by vikdotdev** [comment]
Hey, I've never tried to run it on Ruby 3. Do you have any error messages or it's just that the required version is preventing you from running it? 

Will try to look into it this evening.

**Comment by Inversion-des** [comment]
If you are on Ruby 3+ `gem install` will find some older version of a gem where there was no such `required_ruby_version`, and for me, that version did not work at all…

**Comment by vikdotdev** [comment]
Changed the gemspec `required_ruby_version` to include any future version. I haven't tested it extensively but it should work fine. Feel free to re-open if it doesn't.
